### ISSUE TITLE
Question - VM HA support for Storpool plugin

### ISSUE THREAD

**Issue by rohityadavcloud** [storpool/storpool-cloudstack-integration#4]
Hi @slavkap - does the Storpool plugin support VM HA?

The traditional NFS storage has the heartbeat file [1] which is used during VM HA, is the investigation/fencing mechanisms already handle for VMs using Storpool storage automatically, or have implemented this by some other means (or unsupported)? Thanks.

[1]
https://cwiki.apache.org/confluence/display/CLOUDSTACK/High+Availability+Developer%27s+Guide

**Comment by slavkap** [comment]
Hi @rohityadavcloud, adding @venko-storpool-com, he will be able to answer

**Comment by venko-storpool-com** [comment]
Hi @rohityadavcloud,

There is no code specific for HA in the StorPool plugin. You need a (small) NFS primary storage for the heartbeat in order to enable VM HA.
